name: automerge
on:
  pull_request:
    types: [opened, labeled, synchronize, reopened, ready_for_review]
permissions:
  pull-requests: write
  contents: write
jobs:
  automerge:
    # Auto-merge Dependabot PRs for minor/patch updates after checks pass
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
